package com.clevertap.pushtemplates;

@SuppressWarnings("WeakerAccess")
public class Constants {
    public static final String LOG_TAG = "PTLog";
    public static final String WZRK_ACTIONS = "wzrk_acts";
    public static final String WZRK_CHANNEL_ID = "wzrk_cid";
    public static final String WZRK_PUSH_ID = "wzrk_pid";
    public static final String WZRK_DL = "wzrk_dl";
    public static final String WZRK_FROM_KEY = "wzrk_from";
    public static final String WZRK_FROM = "CTPushNotificationReceiver";
    public static final int EMPTY_NOTIFICATION_ID = -1000;
    public static final String NOTIF_TAG = "wzrk_pn";
    public static final String ICON_BASE_URL = "http://static.wizrocket.com/android/ico/";
    public static final String LABEL_NOTIFICATION_ICON = "CLEVERTAP_NOTIFICATION_ICON";
    public static final String PT_ID = "pt_id";
    public static final String PT_NOTIF_ICON = "pt_ico";
    public static final String PT_TITLE = "pt_title";
    public static final String PT_MSG = "pt_msg";
    public static final String PT_MSG_SUMMARY = "pt_msg_summary";
    public static final String PT_TITLE_COLOR = "pt_title_clr";
    public static final String PT_MSG_COLOR = "pt_msg_clr";
    public static final String PT_BG = "pt_bg";
    public static final String PT_BIG_IMG = "pt_big_img";
    public static final String PT_SMALL_IMG = "pt_small_img";
    public static final String PT_JSON = "pt_json";
    public static final String PT_BUY_NOW_DL = "pt_buy_now_dl";
    public static final String PT_DEFAULT_DL = "pt_default_dl";
    public static final String PT_SMALL_VIEW = "pt_small_view";
    public static final String PT_TIMER_THRESHOLD = "pt_timer_threshold";
    public static final String PT_INPUT_LABEL = "pt_input_label";
    public static final String PT_INPUT_KEY = "pt_input_reply";
    public static final String PT_INPUT_FEEDBACK = "pt_input_feedback";
    public static final int PT_INPUT_TIMEOUT = 1000;
    public static final String PT_NOTIF_ID = "notificationId";
    public static final String PT_INPUT_AUTO_OPEN = "pt_input_auto_open";
    public static final String PT_EVENT_NAME_KEY = "pt_event_name";
    public static final String PT_EVENT_PROPERTY_KEY = "pt_event_property";
    public static final String PT_EVENT_PROPERTY_SEPERATOR = "pt_event_property_";
    public static final String PT_DISMISS_ON_CLICK ="pt_dismiss_on_click";
    public static final String PT_CHRONO_TITLE_COLOUR = "pt_chrono_title_clr";
    public static final String PT_VIDEO_URL = "pt_video_url";
    public static final String PT_PRODUCT_DISPLAY_ACTION = "pt_product_display_action";
    public static final String PT_PRODUCT_DISPLAY_ACTION_COLOUR = "pt_product_display_action_clr";
    public static final String PT_TIMER_END = "pt_timer_end";
    public static final String PT_TIMER_SPLIT = "$D_";
    public static final int PT_TIMER_MIN_THRESHOLD = 10;
    public static final String PT_BIG_IMG_ALT = "pt_big_img_alt";
    public static final String PT_TITLE_ALT = "pt_title_alt";
    public static final String PT_MSG_ALT = "pt_msg_alt";
    public static final String PT_PRODUCT_DISPLAY_LINEAR = "pt_product_display_linear";
}
